### ISSUE TITLE
wgLogoUsage

### ISSUE THREAD

**Issue by Steinsplitter** [Krinkle/ts-krinkle-misc#4]
Please move the following tool to toolslabs:
https://tools.wmflabs.org/krinkle-redirect/wgLogoUsage/
Thank you.

**Comment by Krinkle** [comment]
I've updated the decommissioning note at <https://github.com/Krinkle/ts-krinkle-misc#wglogousage>:

> Obsolete now that project logos are stored the [operations/mediawiki-config repository](https://github.com/wikimedia/operations-mediawiki-config).

For the purpose of auto-protect, this tool was no longer needed as logos are now configured in the MediaWiki software and stored directly in a secure way allowing performant access from the `static` wikimedia.org storage space.

If you're interested at personal level, all files are stored in this directory:
https://github.com/wikimedia/operations-mediawiki-config/tree/master/w/static/images/project-logos

Which is mounted on all Wikimedia wiki domains, e.g. like so:
> https://www.wikimedia.org/static/images/project-logos/commonswiki.png
> https://en.wikipedia.org/static/images/project-logos/commonswiki.png
